# Generated by Django 3.0.3 on 2020-02-11 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(upload_to='shop_pics'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('street', models.CharField(max_length=300)),
                ('zip', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=300)),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_shop.Shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'index_together': {('user', 'shop_item')},
            },
        ),
    ]
